[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.6", features = ["postgres"] }
dotenv = "0.15.0"

[dev-dependencies]
diesel_cli = { version = "2.1.1", features = ["postgres"] }